version: 0.2

phases:
  install:
    commands:
      # Install nodemon
      -npm install -g nodemon
      # Install dependencies needed for running tests
      - npm install

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
